include: package:very_good_analysis/analysis_options.7.0.0.yaml

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    invalid_annotation_target: ignore
    document_ignores: ignore
    avoid_catches_without_on_clauses: ignore

linter:
  rules:
    public_member_api_docs: false
